WhiteLagoon.Web/Controllers/VillaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;

namespace WhiteLagoon.Web.Controllers
{
    [Authorize]
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var villaList = _unitOfWork.Villa.GetAll();
            return View(villaList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Villa villa)
        {
            if(ModelState.IsValid)
            {
                if(villa.Name == villa.Description)
                {
                    ModelState.AddModelError("name", "The name cannot be the same as the description");
                    return View(villa);
                }
                if (ModelState.IsValid)
                {
                    if(villa.Image != null)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(villa.Image.FileName);
                        string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");

                        using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                        villa.Image.CopyTo(fileStream);
                        villa.ImageUrl = @"\images\VillaImage\" + fileName;
                    }
                    else
                    {
                        villa.ImageUrl = "https://placeholder.co/600x400";
                    }
                }
                _unitOfWork.Villa.Add(villa);
                _unitOfWork.Save();
                TempData["success"] = "The Villa has been created succesfully.";
                return RedirectToAction(nameof(Index));
            }

            return View(villa);
        }

        public IActionResult Edit(int villaId) 
        {
            Villa villa = _unitOfWork.Villa.Get(u=> u.Id == villaId);
            if (villa == null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villa);
        }

        [HttpPost]
        public IActionResult Edit(Villa villa)
        {
            if(ModelState.IsValid)
            {
				if (villa.Name == villa.Description)
				{
					ModelState.AddModelError("name", "The name cannot be the same as the description");
					return View(villa);
				}

                if(villa.ImageUrl != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(villa.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");

                    if(!string.IsNullOrEmpty(villa.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, villa.ImageUrl.TrimStart('\\'));

                        if(System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    villa.Image.CopyTo(fileStream);

                    villa.ImageUrl = @"\images\VillaImage\" + fileName;
                }

                _unitOfWork.Villa.Update(villa);
                _unitOfWork.Save();
                TempData["success"] = "The Villa has been edited succesfully.";
                return RedirectToAction("Index");

			}
            return View(villa);
        }

        public IActionResult Delete(int villaId)
        {
			Villa villaFromDb = _unitOfWork.Villa.Get(x => x.Id == villaId);

			if (villaFromDb is null)
			{
				return RedirectToAction("Error", "Home");
			}
            return View(villaFromDb);
        }

        [HttpPost]
        public IActionResult Delete(Villa villa)
        {
            Villa? villafromDb = _unitOfWork.Villa.Get(x => x.Id == villa.Id);
            if (villafromDb is not null)
            {
                if (!string.IsNullOrEmpty(villafromDb.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, villafromDb.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork.Villa.Delete(villafromDb);
				_unitOfWork.Save();
                TempData["success"] = "Villa deleted successfully";
				return RedirectToAction("Index");
			}
            return RedirectToAction("Error","Home");
        }
    }
}

WhiteLagoon.Web/Views/Villa/Create.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-success bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Create Villa</h2>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<div class="p-3">
				<div asp-validation-summary="ModelOnly"></div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Name" class="form-control border shadow" /> 
					<label asp-for="Name" class="ms-2"></label>
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Description" class="form-control border shadow" />
					<label asp-for="Description" class="ms-2"></label>
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="SquareFoot" class="form-control border shadow" />
					<label asp-for="SquareFoot" class="ms-2"></label>
					<span asp-validation-for="SquareFoot" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Price" class="form-control border shadow" />
					<label asp-for="Price" class="ms-2"></label>
					<span asp-validation-for="Price" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Occupancy" class="form-control border shadow" />
					<label asp-for="Occupancy" class="ms-2"></label>
					<span asp-validation-for="Price" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="ImageUrl" hidden class="form-control border shadow" />
					<input asp-for="Image" class="form-control border shadow" />
					<label asp-for="ImageUrl" class="ms-2"></label>
					<span asp-validation-for="ImageUrl" class="text-danger"></span>
				</div>
				<div class="row pt-2">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-success w-100">
							<i class="bi bi-check-circle"> Confirm</i>
						</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
							<i class="bi bi-x-circle"> Cancel</i>
						</a>
					</div>
				</div>

			</div>
		</form>
	</div>
</div>

WhiteLagoon.Web/Views/Villa/Delete.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-success bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Delete Villa</h2>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row">
			<input asp-for="Id" hidden />
			<div class="col-10">
			<div class="p-3">
				<div asp-validation-summary="ModelOnly"></div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Name" disabled class="form-control border shadow" />
					<label asp-for="Name" class="ms-2"></label>
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Description" disabled class="form-control border shadow" />
					<label asp-for="Description" class="ms-2"></label>
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="SquareFoot" disabled class="form-control border shadow" />
					<label asp-for="SquareFoot" class="ms-2"></label>
					<span asp-validation-for="SquareFoot" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Price" disabled class="form-control border shadow" />
					<label asp-for="Price" class="ms-2"></label>
					<span asp-validation-for="Price" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Occupancy" disabled class="form-control border shadow" />
					<label asp-for="Occupancy" class="ms-2"></label>
					<span asp-validation-for="Price" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="ImageUrl" disabled class="form-control border shadow" />
					<label asp-for="ImageUrl" class="ms-2"></label>
					<span asp-validation-for="ImageUrl" class="text-danger"></span>
				</div>
				<div class="row pt-2">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-danger w-100">
							<i class="bi bi-trash-fill"> Confirm</i>
						</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
							<i class="bi bi-x-circle"> Cancel</i>
						</a>
					</div>
				</div>

			</div>
			</div>
			<div class="col-2">
				<img src="@Model.ImageUrl" width="100%"
					 style="border-radius:5px; border:1px solid #bbb9b9" />
			</div>
		</form>
	</div>
</div>

WhiteLagoon.Web/Views/Villa/Edit.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-success bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Edit Villa</h2>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<input asp-for="Id" hidden />
			<div class="col-10">
				<div class="p-3">
					<div asp-validation-summary="ModelOnly"></div>
					<div class="form-floating py-2 col-12">
						<input asp-for="Name" class="form-control border shadow" />
						<label asp-for="Name" class="ms-2"></label>
						<span asp-validation-for="Name" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="Description" class="form-control border shadow" />
						<label asp-for="Description" class="ms-2"></label>
						<span asp-validation-for="Description" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="SquareFoot" class="form-control border shadow" />
						<label asp-for="SquareFoot" class="ms-2"></label>
						<span asp-validation-for="SquareFoot" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="Price" class="form-control border shadow" />
						<label asp-for="Price" class="ms-2"></label>
						<span asp-validation-for="Price" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="Occupancy" class="form-control border shadow" />
						<label asp-for="Occupancy" class="ms-2"></label>
						<span asp-validation-for="Occupancy" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="ImageUrl" hidden class="form-control border shadow" />
						<input asp-for="Image" class="form-control border shadow" />
						<label asp-for="ImageUrl" class="ms-2"></label>
						<span asp-validation-for="ImageUrl" class="text-danger"></span>
					</div>
					<div class="row pt-2">
						<div class="col-6 col-md-3">
							<button type="submit" class="btn btn-success w-100">
								<i class="bi bi-check-circle"> Confirm</i>
							</button>
						</div>
						<div class="col-6 col-md-3">
							<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
								<i class="bi bi-x-circle"> Cancel</i>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-2">
				<img src="@Model.ImageUrl" width="100%"
				style="border-radius:5px; border:1px solid #bbb9b9"/>
			</div>
			
		</form>
	</div>
</div>

WhiteLagoon.Web/Views/Villa/Index.cshtml
@model IEnumerable<Villa>

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-success bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Villa List</h2>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<div class="row pb-3">
			<div class="col-6 offset-6 text-end">
				<a asp-controller="Villa" asp-action="Create" class="btn btn-secondary bi bi-plus-circle"> Create New Villa</a>
			</div>
		</div>

		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Price</th>
					<th>Occupancy</th>
					<th>Square Foot</th>
					<th>Description</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var villa in Model)
				{
					<tr>
						<td>@villa.Name</td>
						<td>@villa.Price</td>
						<td>@villa.Occupancy</td>
						<td>@villa.SquareFoot</td>
						<td>@villa.Description</td>
						<td>
							<div class="w-75 btn-group">
								<a asp-controller="Villa" asp-action="Edit" asp-route-villaId="@villa.Id" class="btn btn-success mx-2">
									<i class="bi bi-pencil-square"></i> Edit
							    </a>
								<a asp-controller="Villa" asp-action="Delete" asp-route-villaId="@villa.Id" class="btn btn-danger mx-2">
									<i class="bi bi-trash-fill"></i> Delete
								</a>
							</div>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>