WhiteLagoon.Web/Controllers/AmenityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Utility;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;
using WhiteLagoon.Web.ViewModel;

namespace WhiteLagoon.Web.Controllers
{
    [Authorize(Roles = Sd.Role_Admin)]
    public class AmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public AmenityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {

            var villaNumberList = _unitOfWork.Amenity.GetAll(include:"Villa");
            return View(villaNumberList);
        }

        public IActionResult Create()
        {

			AmenityVm dropdownVilla = new()
			{
				DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString()
				})
			};
			return View(dropdownVilla);
        }

        [HttpPost]
        public IActionResult Create(AmenityVm amenityVm)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Amenity.Add(amenityVm.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "The Villa Number has been created succesfully.";
                return RedirectToAction("Index");
            }

			amenityVm.DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
			{
				Text = u.Name,
				Value = u.Id.ToString()
			});


            ModelState.AddModelError("DropdownVilla", "Villa Id is required");
			return View(amenityVm);
        }

        public IActionResult Edit(int amenityId)
        {
            AmenityVm amenityVm = new()
            {
                DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Amenity = _unitOfWork.Amenity.Get(u => u.Id == amenityId),
            };
        
            if (amenityVm == null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(amenityVm);
        }

        [HttpPost]
        public IActionResult Edit(AmenityVm amenityVm)
        {
            var amenityExist = _unitOfWork.Amenity.Any( u=> u.Id == amenityVm.Amenity.Id);

			if (ModelState.IsValid && amenityExist)
			{
                _unitOfWork.Amenity.Update(amenityVm.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "The Amenity has successfully edited.";
				return RedirectToAction("Index");
			}

            if (amenityExist)
            {
                amenityVm.DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString()
				});

				TempData["error"] = "The Amenity already exist.";
				return View(amenityVm);
			}

            ModelState.AddModelError("DropdownVilla", "The Villa id is not valid");
            return RedirectToAction("Index");
			
        }

        public IActionResult Delete(int amenityId)
        {
            AmenityVm amenityVm = new()
            {
                
                DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
				Amenity = _unitOfWork.Amenity.Get(x => x.Id == amenityId)
			};

            if (amenityVm.Amenity is null)
			{
				return RedirectToAction("Error", "Home");
			}

            return View(amenityVm);
        }

        [HttpPost]
        public IActionResult Delete(AmenityVm amenityVm)
        {
            
            Amenity amenityFromDb = _unitOfWork.Amenity.Get(x => x.Id == amenityVm.Amenity.Id);
            if (amenityFromDb is not null)
            {
				_unitOfWork.Amenity.Delete(amenityFromDb);
				_unitOfWork.Save();
                TempData["success"] = "the VillaNumber is deleted successfully";
				return RedirectToAction("Index");
			}

            return RedirectToAction("Error","Home");
        }
    }
}

WhiteLagoon.Web/Controllers/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Utility;
using WhiteLagoon.Domain.Entities;

namespace WhiteLagoon.Web.Controllers
{
    public class BookingController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public BookingController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult FinalizeBooking(int villaId, string checkInDate, int nights)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ApplicationUser user = _unitOfWork.User.Get(u=> u.Id == userId);

            DateOnly parsedCheckInDate = DateOnly.Parse(checkInDate);
            Booking booking = new()
            {
                VillaId = villaId,
                Villa = _unitOfWork.Villa.Get(u => u.Id == villaId, include: "VillaAmenities"),
                CheckinDate = parsedCheckInDate,
                Nights = nights,
                CheckoutDate = parsedCheckInDate.AddDays(nights),
                UserId = userId,
                Phone = user.PhoneNumber,
                Email  =user.Email,
                Name = user.Name
            };

            booking.TotalCost = booking.Villa.Price * nights;
            
            return View(booking);
        }
        [Authorize]
        [HttpPost]
        public IActionResult FinalizeBooking(Booking booking)
        {
            var villa = _unitOfWork.Villa.Get(u => u.Id == booking.VillaId);
            booking.TotalCost = villa.Price * booking.Nights;
            booking.Status = Sd.StatusPending;

            _unitOfWork.Booking.Add(booking);
            _unitOfWork.Save();

            return RedirectToAction(nameof(BookingConfirmation), new { bookingId = booking.Id});
        }

        [Authorize]
        public IActionResult BookingConfirmation(int bookingId)
        {
            return View(bookingId);
        }
    }
}

WhiteLagoon.Web/Controllers/VillaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;

namespace WhiteLagoon.Web.Controllers
{
    [Authorize]
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var villaList = _unitOfWork.Villa.GetAll();
            return View(villaList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Villa villa)
        {
            if(ModelState.IsValid)
            {
                if(villa.Name == villa.Description)
                {
                    ModelState.AddModelError("name", "The name cannot be the same as the description");
                    return View(villa);
                }
                if (ModelState.IsValid)
                {
                    if(villa.Image != null)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(villa.Image.FileName);
                        string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");

                        using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                        villa.Image.CopyTo(fileStream);
                        villa.ImageUrl = @"\images\VillaImage\" + fileName;
                    }
                    else
                    {
                        villa.ImageUrl = "https://placeholder.co/600x400";
                    }
                }
                _unitOfWork.Villa.Add(villa);
                _unitOfWork.Save();
                TempData["success"] = "The Villa has been created succesfully.";
                return RedirectToAction(nameof(Index));
            }

            return View(villa);
        }

        public IActionResult Edit(int villaId) 
        {
            Villa villa = _unitOfWork.Villa.Get(u=> u.Id == villaId);
            if (villa == null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villa);
        }

        [HttpPost]
        public IActionResult Edit(Villa villa)
        {
            if(ModelState.IsValid)
            {
				if (villa.Name == villa.Description)
				{
					ModelState.AddModelError("name", "The name cannot be the same as the description");
					return View(villa);
				}

                if(villa.ImageUrl != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(villa.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");

                    if(!string.IsNullOrEmpty(villa.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, villa.ImageUrl.TrimStart('\\'));

                        if(System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    villa.Image.CopyTo(fileStream);

                    villa.ImageUrl = @"\images\VillaImage\" + fileName;
                }

                _unitOfWork.Villa.Update(villa);
                _unitOfWork.Save();
                TempData["success"] = "The Villa has been edited succesfully.";
                return RedirectToAction("Index");

			}
            return View(villa);
        }

        public IActionResult Delete(int villaId)
        {
			Villa villaFromDb = _unitOfWork.Villa.Get(x => x.Id == villaId);

			if (villaFromDb is null)
			{
				return RedirectToAction("Error", "Home");
			}
            return View(villaFromDb);
        }

        [HttpPost]
        public IActionResult Delete(Villa villa)
        {
            Villa? villafromDb = _unitOfWork.Villa.Get(x => x.Id == villa.Id);
            if (villafromDb is not null)
            {
                if (!string.IsNullOrEmpty(villafromDb.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, villafromDb.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork.Villa.Delete(villafromDb);
				_unitOfWork.Save();
                TempData["success"] = "Villa deleted successfully";
				return RedirectToAction("Index");
			}
            return RedirectToAction("Error","Home");
        }
    }
}

WhiteLagoon.Web/Controllers/VillaNumberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;
using WhiteLagoon.Web.ViewModel;

namespace WhiteLagoon.Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public VillaNumberController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            //var villaNumberList = _db.VillaNumbers.ToList();
            //var villaNumberList = _db.VillaNumbers.Include(u => u.Villa).ToList();
            var villaNumberList = _unitOfWork.VillaNumber.GetAll(include: "Villa");
            return View(villaNumberList);
        }

        public IActionResult Create()
        {
			//IEnumerable<SelectListItem> dropdownVilla = _db.Villas.ToList().Select(u => new SelectListItem
			//{
			//    Text = u.Name,
			//    Value = u.Id.ToString()
			//});
			VillaNumberVm dropdownVilla = new()
			{
				DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString()
				})
			};
			return View(dropdownVilla);
        }

        [HttpPost]
        public IActionResult Create(VillaNumberVm villaNumberVm)
        {
            //var villaNumberExist = _db.VillaNumbers.Any(u => u.Villa_Number == villaNumberVm.VillaNumber.Villa_Number);
            var villaNumberExist = _unitOfWork.VillaNumber.Any(u => u.Villa_Number == villaNumberVm.VillaNumber.Villa_Number);

            if (ModelState.IsValid && !villaNumberExist && villaNumberVm.VillaNumber.VillaId != 0)
            {
                _unitOfWork.VillaNumber.Add(villaNumberVm.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "The Villa Number has been created succesfully.";
                return RedirectToAction("Index");
            }

			villaNumberVm.DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
			{
				Text = u.Name,
				Value = u.Id.ToString()
			});

			if (villaNumberExist)
            {
				TempData["error"] = "This Villa Number already exists.";

				return View(villaNumberVm);
			}

            ModelState.AddModelError("DropdownVilla", "Villa Id is required");
			return View(villaNumberVm);
        }

        public IActionResult Edit(int villaNumberId)
        {
            VillaNumberVm villaNumberVm = new()
            {
                DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId),
            };
        
            if (villaNumberVm == null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villaNumberVm);
        }

        [HttpPost]
        public IActionResult Edit(VillaNumberVm villaNumberVm)
        {
            var villaNumberExist = _unitOfWork.VillaNumber.Any( u=> u.Villa_Number == villaNumberVm.VillaNumber.Villa_Number);

			if (ModelState.IsValid && villaNumberExist)
			{
                _unitOfWork.VillaNumber.Update(villaNumberVm.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "The VillaNumber has successfully edited.";
				return RedirectToAction("Index");
			}

            if (villaNumberExist)
            {
                villaNumberVm.DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString()
				});

				TempData["error"] = "The VillaNumber already exist.";
				return View(villaNumberVm);
			}

            ModelState.AddModelError("DropdownVilla", "The Villa id is not valid");
            return RedirectToAction("Index");
			
        }

        public IActionResult Delete(int villaNumberId)
        {
            VillaNumberVm villaNumberVm = new()
            {
                VillaNumber = _unitOfWork.VillaNumber.Get(x => x.Villa_Number == villaNumberId),
                DropdownVilla = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
            };

            if (villaNumberVm.VillaNumber is null)
			{
				return RedirectToAction("Error", "Home");
			}

            return View(villaNumberVm);
        }

        [HttpPost]
        public IActionResult Delete(VillaNumberVm villaNumberVm)
        {
            
            VillaNumber villaNumberfromDb = _unitOfWork.VillaNumber.Get(x => x.Villa_Number == villaNumberVm.VillaNumber.Villa_Number);
            if (villaNumberfromDb is not null)
            {
				_unitOfWork.VillaNumber.Delete(villaNumberfromDb);
				_unitOfWork.Save();
                TempData["success"] = "the VillaNumber is deleted successfully";
				return RedirectToAction("Index");
			}

            return RedirectToAction("Error","Home");
        }
    }
}

WhiteLagoon.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhiteLagoon.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WhiteLagoon.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.jpg" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content-Manager
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link" asp-area="" asp-controller="Villa" asp-action="Index">Villa</a></li>
                                <li><a class="nav-link" asp-area="" asp-controller="VillaNumber" asp-action="Index">VillaNumber</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="nav-link" asp-area="" asp-controller="Amenity" asp-action="Index">Amenity</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main">
            <div class="loading spinner" style="display:none;">
                Loading
            </div>
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center">
            Made by Edoardo following the DotNetMastery course
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js" integrity="sha512-X/YkDZyjTf4wyc2Vy16YGCPHwAY8rZJY+POgokZjQB2mhIRFJCckEGc6YyX9eNsPfn0PzThEuNs+uaomE5CO6A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WhiteLagoon.Web/Views/Shared/_Notification.cshtml
@if (TempData["error"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["success"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

WhiteLagoon.Web/Views/Shared/_VillaDetail.cshtml
@model Villa

<div class="row">
    <div class="col-12 col-md-5">
        <img src="@Model.ImageUrl" style="border-radius:10px;" width="100%" />
    </div>
    <div class="col-12 col-md-7">
        <div class="row p-2">
            <div class="col-12">
                <p class="card-title text-warning" style="font-size:xx-large">@Model.Name</p>
                <p class="card-text" style="font-size:large">
                    Html.Raw(@Model.Description)
                </p>
                @if (Model.VillaAmenities != null && Model.VillaAmenities.Count() > 0)
                {
                    <p class="h5 text-white">Villa Amenities</p>
                    <ul>
                        @foreach (var amenity in Model.VillaAmenities)
                        {
                            <li>@amenity.Name</li>
                        }

                    </ul>
                }

            </div>
        </div>
        <div class="row col-12">
            <span class="text-end p-0 pt-3 m-0">
                <span class="float-right">Max Occupancy : @Model.Occupancy adults </span><br />
                <span class="float-right pt-1">Villa Size : @Model.SquareFoot sqft</span><br />
                <p class="text-warning font-weight-bold pt-1">
                    USD
                    <span style=" #ff6a00">
                        @Model.Price.ToString("c") / night
                    </span>
                </p>
            </span>
        </div>
    </div>
</div>

WhiteLagoon.Web/Views/Shared/_VillaList.cshtml
@model HomeVm
<div id="VillasList">
    <div class="row px-lg-5 m-lg-4 m-sm-0 px-sm-0" style="--bs-gutter-x:0">

        @foreach (var villa in Model.VillaList)
        {
            @* Card *@
            <div class="p-4 col-md-12 col-lg-6">
                <div class="row" style="border-radius:5px; border: 1px solid #aaa">
                    <div class="col-4 p-2">
                        <img class="d-block w-100" style="border-radius:5px;" src="@villa.ImageUrl">
                    </div>
                    <div class="col-8">
                        <div class="d-flex justify-content-between">
                            <p class="card-title text-warning" style="font-size:xx-large">@villa.Name</p>
                            <div class="pt-2">
                                <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target='#exampleModal-@(villa.Id)'>
                                    Details
                                </button>
                            </div>
                        </div>
                        <p class="card-text">
                            @Html.Raw(@villa.Description)
                        </p>
                    </div>
                    <div class="col-12">
                        <div class="row pb-3 pt-2">
                            <div class="col-4">
                                @if (Model.CheckInDate > DateOnly.FromDateTime(DateTime.Now))
                                {
                                    if (villa.IsAvailable)
                                    {

                                        <a asp-controller="Booking" asp-action="FinalizeBooking"
                                           asp-route-villaId="@villa.Id" asp-route-checkInDate="@Model.CheckInDate.ToString("yyyy-MM-dd")"
                                           asp-route-nights="@Model.Nights"
                                           class="btn btn-success form-control btn-block">Book</a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-outline-danger form-control btn-block">Sold Out</a>
                                    }
                                }
                            </div>
                            <div class="col-4">
                                <span class="">Max Occupancy : @villa.Occupancy adults </span><br />
                                <span class=" pt-1">Villa Size : @villa.SquareFoot sqft</span><br />
                            </div>
                            <div class="col-4">
                                <span class="text-warning float-end font-weight-bold pt-1" style="font-size:25px;">
                                    USD
                                    <span style="border-bottom:1px solid #ff6a00">
                                        @villa.Price.ToString("c")
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @* Modal *@
            <div class="modal fade" id="exampleModal-@(villa.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-xl" style="border: 1px solid #aaa; border-radius:7px;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-3 text-success" id="exampleModalLabel">Villa Details - @villa.Name</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body m-0">
                            @* Details *@

                            <partial name="_VillaDetail" model="@villa" />

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>
        }

    </div>
</div>